server:
  port: ${SERVER_PORT:8520}
  servlet:
    context-path:  ${CONTEXT_PATH:/yuheng-api}
spring:
  application:
    name: yuheng-api
  data:
    redis:
      host: ${SPRING_REDIS_HOST:xixi.vip}
      password: ${SPRING_REDIS_PASSWORD:xixiRedisMima1996!}
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
      url: ${SPRING_DATASOURCE_URL:jdbc:mysql://titi.vip:3306/yuheng?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:123456}
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@172.17.0.1:1521/orclpdb1}
#    username: ${SPRING_DATASOURCE_USERNAME:eams_dev}
#    password: ${SPRING_DATASOURCE_PASSWORD:eams}
#    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cache:
    redis:
      time-to-live: 600000
    type: caffeine
    caffeine:
        spec: maximumSize=2000,expireAfterAccess=600s
jwt:
  secret: "bGl1eXVpc2Fnb2Rib3k=" # 至少 32 字符
  expiration: 1800000 # 半个小时
  refresh-expiration: 86400000 # 24 小时

#logging:
#  level:
#    root: debug
# Resilience4j 配置
resilience4j:
  ratelimiter:
    instances:
      apiRateLimiter:
        limit-for-period: 2000 # 每秒允许的请求数
        limit-refresh-period: 1s # 刷新周期
        timeout-duration: 2000ms # 获取令牌的超时时间
  circuitbreaker:
    instances:
      apiCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 100 # 滑动窗口大小
        failure-rate-threshold: 50 # 失败率阈值，超过则熔断
        wait-duration-in-open-state: 5s # 熔断后等待时间
        permitted-number-of-calls-in-half-open-state: 10 # 半开状态允许的调用数
        automatic-transition-from-open-to-half-open-enabled: true # 自动从熔断到半开状态