server:
  port: ${SERVER_PORT:8520}
  servlet:
    context-path:  ${CONTEXT_PATH:/yuheng-api}
spring:
  application:
    name: yuheng-api
  data:
    redis:
      host: ${SPRING_REDIS_HOST:xixi.vip}
      password: ${SPRING_REDIS_PASSWORD:123456}
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://titi.vip:3306/gateway?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true}
  #    username: ${SPRING_DATASOURCE_USERNAME:root}
  #    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@xixi.vip:1521/orclpdb1}
    username: ${SPRING_DATASOURCE_USERNAME:eams_dev}
    password: ${SPRING_DATASOURCE_PASSWORD:eams}
    driver-class-name: oracle.jdbc.OracleDriver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
jwt:
  secret: "my-super-secret-key-for-shiro-jwt-integration-must-be-long-enough" # 至少 32 字符
  expiration: 3600000 # 1 小时